Repository bank-vaults/bank-vaults, pull requests merged in 2018-11, with the labels that each got.

#198 Fix race condition between token list/lookup/removal
  pkg/auth/tokenstore.go
Labels: bug

#199 Add etcdAnnotations field to Vault CR to annotate etcdcluster
  operator/deploy/cr-etcd-ha.yaml
  operator/pkg/apis/vault/v1alpha1/types.go
  operator/pkg/stub/handler.go
Labels: community

#212 Add auth-delegator binding to vault-operator service account
  cmd/examples/main.go
  operator/deploy/rbac.yaml
Labels: bug

#213 File based unsealing
  README.md
  cmd/bank-vaults/main.go
  cmd/bank-vaults/util.go
  pkg/kv/file/file.go
Labels: unseal

#216 Fix for in faulty leader state in metrics
  operator/pkg/stub/handler.go
  pkg/vault/operator_client.go
Labels: bug, prometheus
