Repository bank-vaults/bank-vaults, pull requests merged in 2018-09, with the labels that each got.

#145 Handling kubernetes auth config
  pkg/vault/vault.go
  vault-config.yml
Labels: auth, community, kubernetes

#151 Fix Dockerfiles after vendoring
  Dockerfile
  Dockerfile.operator
Labels: build

#153 Fix Kubernetes auth configuration
  pkg/vault/vault.go
Labels: auth

#157 Support StatefuleSet upgrade with workaround
  cmd/bank-vaults/unseal.go
  operator/deploy/cr-etcd-ha.yaml
  operator/pkg/apis/vault/v1alpha1/types.go
  operator/pkg/stub/handler.go
  pkg/vault/vault.go
Labels: kubernetes

#162 Improve Azure file based auth
  Gopkg.lock
  operator/deploy/cr-azure.yaml
  pkg/kv/azurekv/iam.go
  pkg/kv/azurekv/keyvault.go
Labels: azure
