Repository bank-vaults/bank-vaults, pull requests merged in 2018-10, with the labels that each got.

#168 Refactor package structure to be more Golang idiomatic
  README.md
  cmd/examples/main.go
  pkg/auth/auth.go
  pkg/auth/tokenstore.go
  pkg/auth/tokenstore_test.go
  pkg/db/database.go
  pkg/vault/client.go
  pkg/vault/operator_client.go
Labels: enhancement

#174 operator: add generic fluentd logging sidecar
  operator/pkg/apis/vault/v1alpha1/types.go
  operator/pkg/stub/handler.go
Labels: community, enhancement, logging

#177 Configurer needs to check if Vault is active before configuring
  cmd/bank-vaults/configure.go
  pkg/vault/operator_client.go
Labels: configurer

#184 Add ability to use existing etcd cluster
  operator/README.md
  operator/pkg/apis/vault/v1alpha1/types.go
  operator/pkg/stub/handler.go
Labels: etcd

#183 Add PKI config to example
  README.md
Labels: pki

#192 Add gcp auth backend support
  README.md
  pkg/vault/operator_client.go
Labels: auth, community

#193 Support child dict on secrets engine's configuration
  pkg/vault/operator_client.go
Labels: community, secret-engine

#195 make Vault CA certificate reloadable by client
  cmd/examples/main.go
  pkg/vault/client.go
Labels: vault
