Repository bank-vaults/bank-vaults, pull requests merged in 2018-12, with the labels that each got.

#218 Make k8s incluster config based auth future proof
  pkg/vault/client.go
Labels: kubernetes

#248 operator: support Volumes in Vault CRD
  operator/README.md
  operator/deploy/cr.yaml
  operator/pkg/apis/vault/v1alpha1/types.go
  operator/pkg/stub/handler.go
Labels: operator

#250 Make vault-env a static binary
  Dockerfile.vault-env
  deploy/test-deployment.yaml
Labels: bug, webhook

#252 Make vault-configurer use configured securityContext
  operator/pkg/stub/handler.go
Labels: community, enhancement
