Repository bank-vaults/bank-vaults, pull requests merged in 2019-03, with the labels that each got.

#343 [vault-env] added VAULT_* environment sanitization
  cmd/vault-env/main.go
Labels: webhook

#345 example: kv secret engine used for leader election logic
  vault-config.yml
Labels: configurer, documentation

#350 vault-secrets-webhook run as nobody with unprivileged port
  Dockerfile.webhook
  cmd/vault-secrets-webhook/main.go
Labels: webhook

#347 Env update
  cmd/vault-env/main.go
  cmd/vault-secrets-webhook/main.go
Labels: community, webhook

#356 support multiple external ConfigMaps
  cmd/bank-vaults/configure.go
  operator/deploy/config.yaml
  operator/pkg/controller/vault/vault_controller.go
  pkg/vault/operator_client.go
Labels: configurer, enhancement

#361 use VAULT_CLUSTER_INTERFACE to have correct HA Cluster address
  operator/pkg/controller/vault/vault_controller.go
Labels: operator

#366 remove redundant and incorrect active check in new HA setup
  cmd/bank-vaults/configure.go
Labels: bug, configurer

#370 Add support for creating vault configurations as Secrets
  operator/deploy/secret.yaml
  operator/pkg/controller/vault/vault_controller.go
Labels: configurer, operator

#374 always transform sts_account to a string
  pkg/vault/operator_client.go
Labels: aws, configurer

#373 add the ability for custom ports
  operator/deploy/cr-customports.yaml
  operator/pkg/apis/vault/v1alpha1/vault_types.go
  operator/pkg/controller/vault/vault_controller.go
Labels: community, operator

#376 append to the slice, not overwrite the slice
  operator/pkg/controller/vault/vault_controller.go
Labels: operator

#377 getServicePorts should sort the values returned
  operator/deploy/cr-customports.yaml
  operator/pkg/controller/vault/vault_controller.go
Labels: bug, operator

#378 add --once flag to configure and respect VAULT_TOKEN in dev mode
  cmd/bank-vaults/configure.go
  pkg/kv/dev/dev.go
Labels: configurer, enhancement

#385 circle: DOCKER_LATEST=1
  .circleci/config.yml
Labels: build

#379 Prometheus metrics for configurator mode
  cmd/bank-vaults/configure.go
  cmd/bank-vaults/metrics.go
  cmd/bank-vaults/unseal.go
  hack/acceptance-test.sh
  operator/pkg/controller/vault/vault_controller.go
Labels: community, configurer, prometheus
