Repository bank-vaults/bank-vaults, pull requests merged in 2019-01, with the labels that each got.

#253 Remove unnecessary data property.
  cmd/vault-env/main.go
Labels: community

#262 Remove slashes from VERSION variable
  Makefile
Labels: build

#267 Allow to control vault's log level with env
  README.md
  operator/deploy/cr.yaml
  operator/pkg/controller/vault/vault_controller.go
Labels: community, documentation, logging

#268 Add support for nodeAffinity for vault containers
  operator/deploy/cr-nodeAffinity.yaml
  operator/pkg/apis/vault/v1alpha1/vault_types.go
  operator/pkg/controller/vault/vault_controller.go
Labels: community, enhancement

#274 Use `path` when configuring Kubernetes auth roles
  pkg/vault/operator_client.go
Labels: auth

#278 Add support to config secret engine, which nosub-path after config
  README.md
  pkg/vault/operator_client.go
Labels: configurer

#280 Describe how to encrypt root token stored in AWS
  README.md
Labels: community, documentation

#298 operator: update etcd when corresponding part of the CRD changes
  operator/pkg/controller/vault/vault_controller.go
Labels: operator

#310 Watch the entire cluster if the watched namespace is not set
  operator/cmd/manager/main.go
Labels: bug, community

#312 Fix PKI engine TTL configuration example
  README.md
Labels: documentation, pki
