Repository bank-vaults/bank-vaults, pull requests merged in 2020-04, with the labels that each got.

#933 Implement the ability for a CA to persist when the Server certificate needs to be regenerated
  operator/pkg/controller/vault/vault_controller.go
  pkg/sdk/tls/tls.go
  pkg/sdk/tls/tls_integration_test.go
Labels: enhancement, operator, tls

#936 vault-env: fix signal subscription order
  cmd/vault-env/main.go
Labels: webhook

#937 Use string for tlsExpiryTreshold in spec instead of duration
  operator/deploy/cr.yaml
  operator/pkg/apis/vault/v1alpha1/vault_types.go
  operator/pkg/apis/vault/v1alpha1/zz_generated.deepcopy.go
Labels: operator

#941 webhook: upgrade jsonpatch to fix index out of range
  go.mod
  go.sum
Labels: bug, webhook

#943 update aws example
  operator/deploy/cr-aws.yaml
Labels: aws, documentation

#949 operator/tls: Use Data instead of StringData when accessing the previous CA, add log message if the CA has to be rotated
  operator/pkg/controller/vault/vault_controller.go
Labels: bug, operator, tls

#951 add chart linter github action
  .github/workflows/ci.yml
  charts/testing.yaml
Labels: build

#955 add cronjob injection example
  deploy/test-cronjob.yaml
Labels: documentation, webhook

#953 Add custom functions for awskms and file
  go.mod
  internal/configuration/template.go
  operator/deploy/cr-awskms.yaml
  operator/deploy/cr-file.yaml
  operator/deploy/cr-gcpkms.yaml
Labels: operator

#959 add blob template function
  go.mod
  go.sum
  internal/configuration/template.go
  operator/deploy/cr-awskms.yaml
Labels: configurer

#962 prepare for version 1.2.0
  charts/vault-operator/Chart.yaml
  charts/vault-operator/README.md
  charts/vault-operator/values.yaml
  charts/vault-secrets-webhook/Chart.yaml
  charts/vault-secrets-webhook/README.md
  charts/vault-secrets-webhook/values.yaml
  charts/vault/Chart.yaml
  charts/vault/values.yaml
Labels: release
