Repository bank-vaults/bank-vaults, pull requests merged in 2022-12, with the labels that each got.

#1739 Replaced GHA `set-output` with `GITHUB_OUTPUT`
  .github/workflows/docker.yml
  .github/workflows/helm.yml
Labels: dx

#1742 Fix helm release Github Action
  .github/workflows/helm.yml
Labels: github_actions

#1743 webhook: local dev environment facilitation
  Makefile
  deploy/test-configmap-dev.yaml
Labels: webhook

#1753 Release 1.17
  .licensei.toml
  charts/README.md
  charts/vault-operator/Chart.yaml
  charts/vault-secrets-webhook/Chart.yaml
  charts/vault/Chart.yaml
Labels: release
