Repository bank-vaults/bank-vaults, pull requests merged in 2023-07, with the labels that each got.

#1997 Add e2e test startupSecrets cases
  e2e/validate-config-crud/test.sh
  e2e/validate-config-crud/vault-config.yaml
Labels: testing

#1903 configurer: use `azure-sdk-for-go` package
  go.mod
  go.sum
  pkg/kv/azurekv/iam.go
  pkg/kv/azurekv/keyvault.go
Labels: configurer

#2066 Fix AWS KMS encryption context
  cmd/bank-vaults/main.go
  pkg/kv/awskms/awskms.go
Labels: bug, aws

#2071 feat: add back softhsm as a separate stage
  .github/workflows/artifacts.yaml
  Dockerfile
Labels: bug

#2077 fix: user permission issues with softhsm
  Dockerfile
Labels: bug
