Repository bank-vaults/bank-vaults, pull requests merged in 2024-08, with the labels that each got.

#2840 fix: don't set static token_reviewer_jwt
  go.mod
  go.sum
  internal/vault/auth_methods.go
Labels: kind/bug, size/S, area/auth

#2832 chore: change version to dev
  cmd/bank-vaults/main.go
  cmd/template/main.go
Labels: size/XS

#2888 refactor: general codebase improvements
  .github/workflows/ci.yaml
  .github/workflows/e2e.yaml
  .golangci.yml
  ADOPTERS.md
  Makefile
  README.md
  cmd/bank-vaults/common.go
  cmd/bank-vaults/configure.go
  cmd/bank-vaults/gen_docs.go
  cmd/bank-vaults/metrics.go
  cmd/template/main.go
  docker-compose.yaml
  internal/vault/audits.go
  internal/vault/auth_methods.go
  internal/vault/identity_groups.go
  internal/vault/operator_client.go
  internal/vault/plugins.go
  internal/vault/policies.go
  internal/vault/secrets_engines.go
  internal/vault/startup_secrets.go
  pkg/kv/alibabaoss/oss.go
  pkg/kv/awskms/awskms.go
  pkg/kv/azurekv/keyvault.go
  pkg/kv/dev/dev.go
  pkg/kv/gckms/cloudkms.go
  pkg/kv/gcs/gcs.go
  pkg/kv/hsm/hsm.go
  pkg/kv/k8s/k8s.go
  pkg/kv/oci/oci.go
  pkg/kv/ocikms/ocikms.go
  pkg/kv/s3/s3.go
  pkg/kv/vault/vault.go
Labels: kind/enhancement, size/L

#2897 feat: switch from xgo to gorelaser-cross
  .github/workflows/artifacts.yaml
  .goreleaser.yaml
  Makefile
  flake.nix
Labels: kind/enhancement, area/build, size/M

#2902 chore: update go version and packages
  Dockerfile
  flake.nix
  go.mod
  go.sum
Labels: area/dependencies, size/M
