Repository bank-vaults/bank-vaults, pull requests merged in 2024-02, with the labels that each got.

#2498 ci: update dependabot config
  .github/dependabot.yaml
Labels: size/S

#2508 feat: Cancel previous workflow on push
  .github/workflows/ci.yaml
Labels: size/XS

#2504 chore: update bank-vaults deps
  .licensei.toml
  go.mod
  go.sum
Labels: size/XL

#2506 fix: Use correct unseal key name in cofigurer
  internal/vault/operator_client.go
  pkg/kv/awskms/awskms.go
Labels: size/S
